### ISSUE TITLE
Are trained weights in pretrained_models

### ISSUE THREAD

**Issue by 22nicolet** [romainloiseau/Helix4D#2]
Hello,

I want to run the pretrained models for Helixnet with the given command:
python main.py \
  +data=dataset \
  +experiment=ours \
  mode=test \
  model.load_weights="/path/to/trained/weights.ckpt"
Is the path to the trained weights already in the pretrained models folder, or is there another way to run the model? Thanks so much!

**Comment by romainloiseau** [comment]
Hello,

Yes the pretrained weights are in the "pretrained_models" folder.
