### ISSUE TITLE
Methods named compute interactions 

### ISSUE THREAD

**Issue by iris0329** [romainloiseau/Helix4D#6]
Hi, thanks for your awesome work and open source, especially the code which is super neat.

When reading the code, I found the method named "compute_interactions" mentioned at [this line](https://github.com/romainloiseau/Helix4D/blob/main/helix4d/model/voxel/transformer/transformer.py#L238C52-L238C52) 

Could you give me some ideas about the meaning of this method and where it corresponds to the paper?

Best regards

**Comment by romainloiseau** [comment]
The method `compute_interactions` aims at computing the receptive field or each tokens. For a list of tokens V, it computes all the M(v) for v in V. In the paper, _in order to use a sparse attention scheme, we define for each voxel v a spatio-temporal mask M(v) characterized by a radius R and a set of rotation offsets P ⊂ N_, equation 7.

It returns lists `iq` and `ik`, the stacked indices for all queries and keys, and all the relative spatial and temporal shifts in `dxyz16` and `dscanid`.
