### ISSUE TITLE
About bucket

### ISSUE THREAD

**Issue by iris0329** [romainloiseau/Helix4D#7]
Hello, 

Another question is how to understand the "bucket" in the code, the bucket is mentioned so many times in the code.

I didn't find it in the paper so I would appreciate it a lot for your reply.

Best regards

**Comment by romainloiseau** [comment]
Sorry for the misleading name. It refers to the relative positional encoding bins, as in _Wu, K., Peng, H., Chen, M., Fu, J., Chao, H.: Rethinking and improving relative position encoding for vision transformer. ICCV (2021)_

Best
